### ISSUE TITLE
variantForObject: is ignored when different inputs of the same type return different variants

### ISSUE THREAD

**Issue by reyner** [jordanekay/Mensa#7]
The sample project includes a `CollectionViewController` subclass whose `variantForObject:` implementation returns the same variant for all objects of the `PrimeFlag` type. In my project, I’d like to return different variants for different objects of the same type based on certain properties of the object, but it appears that I only get cells that use the first variant returned by this method.

**Comment by reyner** [comment]
Fixes #7

**Comment by jordanekay** [comment]
Fixed in https://github.com/jordanekay/Mensa/commit/e7791eefc0c91258f4151d3c0bc57f8f8c7c69d0.
